import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react'
import type { MemoryCategory, MemoryItem } from '../../types'
import { memoryApi } from '../../services/memoryApi'
import { useApp } from '../../stores/AppContext'
import { Icon } from '../../components/Icon'
import { Button, EmptyState, Field, Input, Spinner, Textarea } from '../../components/ui'
import { ConfirmDialog } from '../../components/ConfirmDialog'

const categories: Array<{ id: MemoryCategory | 'all'; label: string }> = [{ id: 'all', label: 'All memory' }, { id: 'personal', label: 'Personal' }, { id: 'preferences', label: 'Preferences' }, { id: 'important', label: 'Important' }, { id: 'temporary', label: 'Temporary' }]
const blank = { title: '', content: '', category: 'personal' as MemoryCategory }
const SEARCH_LIMIT = 200
export function MemoryPage() {
  const { settings, online } = useApp(); const [items, setItems] = useState<MemoryItem[]>([]); const [query, setQuery] = useState(''); const [category, setCategory] = useState<MemoryCategory | 'all'>('all')
  const [editing, setEditing] = useState<MemoryItem | 'new' | null>(null); const [form, setForm] = useState(blank); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const [confirmation, setConfirmation] = useState<{ kind: 'item'; item: MemoryItem } | { kind: 'all' } | null>(null); const addButtonRef = useRef<HTMLButtonElement>(null)
  const load = async () => { if (!online) { setLoading(false); return } setLoading(true); setError(''); try { const result = await memoryApi.list(query, category === 'all' ? undefined : category); setItems(result.memories) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Memory could not be accessed.') } finally { setLoading(false) } }
  useEffect(() => { const timer = setTimeout(() => void load(), query ? 300 : 0); return () => clearTimeout(timer) }, [query, category, online])
  const openEditor = (item?: MemoryItem) => { setEditing(item ?? 'new'); setForm(item ? { title: item.title, content: item.content, category: item.category } : blank); setError('') }
  const save = async (event: FormEvent) => { event.preventDefault(); if (!form.title.trim() || !form.content.trim()) return; setBusy(true); setError(''); try { if (editing === 'new') await memoryApi.create(form); else if (editing) await memoryApi.update(editing.id, form); setEditing(null); await load() } catch (caught) { setError(caught instanceof Error ? caught.message : 'Memory could not be saved.') } finally { setBusy(false) } }
  const confirmDestruction = async () => { if (!confirmation) return; setBusy(true); try { if (confirmation.kind === 'item') { await memoryApi.remove(confirmation.item.id); setItems(current => current.filter(entry => entry.id !== confirmation.item.id)) } else { await memoryApi.clear(); setItems([]) } setConfirmation(null) } catch (caught) { setError(caught instanceof Error ? caught.message : confirmation.kind === 'item' ? 'Delete failed.' : 'Memory could not be cleared.') } finally { setBusy(false) } }
  const grouped = useMemo(() => categories.slice(1).map(group => ({ ...group, items: items.filter(item => item.category === group.id) })).filter(group => group.items.length), [items])
  if (!settings.memoryEnabled) return <section className="section-page"><PageHeading /><EmptyState title="Memory is paused" description="Xultron is not reading or writing personal memory. Re-enable it under Systems → Privacy." /></section>
  return <section className="section-page"><PageHeading /><div className="memory-toolbar"><label className="search-field"><Icon name="search" /><input type="search" value={query} maxLength={SEARCH_LIMIT} onChange={event => setQuery(event.target.value.slice(0, SEARCH_LIMIT))} placeholder="Search stored memory" aria-label="Search memory" /></label><Button ref={addButtonRef} onClick={() => openEditor()} disabled={!online}><Icon name="plus" /> ADD MEMORY</Button></div>
    <div className="category-tabs" role="tablist" aria-label="Memory categories">{categories.map(item => <button role="tab" aria-selected={category === item.id} className={category === item.id ? 'active' : ''} key={item.id} onClick={() => setCategory(item.id)}>{item.label}</button>)}</div>
    {error && <div className="command-error" role="alert">{error}</div>}{loading ? <div className="center-loader"><Spinner /></div> : !items.length ? <EmptyState title={online ? 'Memory field is clear' : 'Memory unavailable offline'} description={online ? 'Store a preference, personal detail, or important reference that Xultron can use.' : 'Reconnect to search and edit server-backed memory.'} action={online ? <Button variant="secondary" onClick={() => openEditor()}>CREATE FIRST MEMORY</Button> : undefined} /> : <div className="memory-field">{grouped.map(group => <section key={group.id}><header><span>{group.label.toUpperCase()}</span><b>{String(group.items.length).padStart(2, '0')}</b></header>{group.items.map(item => <article className="memory-entry" key={item.id}><div><h3>{item.title}</h3><p>{item.content}</p><small>UPDATED {new Date(item.updatedAt).toLocaleDateString()}</small></div><div className="entry-actions"><button onClick={() => openEditor(item)} aria-label={`Edit ${item.title}`}><Icon name="edit" /></button><button onClick={() => setConfirmation({ kind: 'item', item })} aria-label={`Delete ${item.title}`}><Icon name="trash" /></button></div></article>)}</section>)}</div>}
    {!!items.length && <button className="danger-link" disabled={busy || !online} onClick={() => setConfirmation({ kind: 'all' })}>CLEAR ALL MEMORY</button>}
    {editing && <div className="modal-layer" role="presentation"><div className="modal-panel" role="dialog" aria-modal="true" aria-labelledby="memory-editor-title"><header><div><span className="section-index">MEMORY EDITOR</span><h2 id="memory-editor-title">{editing === 'new' ? 'New memory' : 'Edit memory'}</h2></div><button className="icon-button" onClick={() => setEditing(null)} aria-label="Close editor"><Icon name="close" /></button></header><form onSubmit={save}><Field label="Title"><Input value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} maxLength={120} required autoFocus /></Field><Field label="Category"><select className="field" value={form.category} onChange={event => setForm({ ...form, category: event.target.value as MemoryCategory })}>{categories.slice(1).map(item => <option key={item.id} value={item.id}>{item.label}</option>)}</select></Field><Field label="Content"><Textarea value={form.content} onChange={event => setForm({ ...form, content: event.target.value })} maxLength={5000} rows={7} required /></Field>{error && <div className="inline-error" role="alert">{error}</div>}<div className="form-actions"><Button type="button" variant="ghost" onClick={() => setEditing(null)}>CANCEL</Button><Button type="submit" disabled={busy}>{busy ? <Spinner /> : 'SAVE MEMORY'}</Button></div></form></div></div>}
    <ConfirmDialog open={confirmation !== null} title={confirmation?.kind === 'item' ? `Delete “${confirmation.item.title}”?` : 'Clear all Xultron memory?'} description={confirmation?.kind === 'item' ? 'This retained detail will be permanently removed from your account.' : 'Every stored memory will be permanently removed. This cannot be undone.'} confirmLabel={confirmation?.kind === 'item' ? 'DELETE MEMORY' : 'CLEAR ALL MEMORY'} busy={busy} onCancel={() => setConfirmation(null)} onConfirm={() => void confirmDestruction()} fallbackFocusRef={addButtonRef} />
  </section>
}
function PageHeading() { return <header className="page-heading"><div><span className="section-index">KNOWLEDGE MATRIX / 02</span><h1>Xultron Memory</h1><p>Every retained detail remains visible and under your control.</p></div><div className="heading-mark">M</div></header> }
