import { useEffect, useState, type FormEvent, type ReactNode } from 'react'
import type { AppSettings, ProviderKind, SessionDevice, Device } from '../../types'
import { useApp } from '../../stores/AppContext'
import { authApi } from '../../services/authApi'
import { settingsApi } from '../../services/settingsApi'
import { resetDataUsage } from '../../services/apiClient'
import { formatBytes, useDataUsage } from '../../hooks/useNetwork'
import { Icon, type IconName } from '../../components/Icon'
import { Button, EmptyState, Field, Input, Spinner, Switch } from '../../components/ui'
import { ProviderManager } from './ProviderManager'
import { useLocale } from '../../hooks/useLocale'

type Section = 'general' | 'ai' | 'stt' | 'tts' | 'voice' | 'memory' | 'appearance' | 'network' | 'privacy' | 'account' | 'devices'
const sections: { id: Section; label: string; labelTr: string; icon: IconName }[] = [
  { id: 'general', label: 'General', labelTr: 'Genel', icon: 'settings' }, { id: 'ai', label: 'AI Providers', labelTr: 'AI Sağlayıcıları', icon: 'core' }, { id: 'stt', label: 'STT Providers', labelTr: 'STT Sağlayıcıları', icon: 'mic' }, { id: 'tts', label: 'TTS Providers', labelTr: 'TTS Sağlayıcıları', icon: 'voice' }, { id: 'voice', label: 'Voice', labelTr: 'Ses', icon: 'voice' }, { id: 'memory', label: 'Memory', labelTr: 'Hafıza', icon: 'memory' }, { id: 'appearance', label: 'Appearance', labelTr: 'Görünüm', icon: 'core' }, { id: 'network', label: 'Network', labelTr: 'Ağ', icon: 'signal' }, { id: 'privacy', label: 'Privacy', labelTr: 'Gizlilik', icon: 'shield' }, { id: 'account', label: 'Account', labelTr: 'Hesap', icon: 'user' }, { id: 'devices', label: 'Devices', labelTr: 'Cihazlar', icon: 'devices' },
]
export function SettingsPage() {
  const { online } = useApp(); const [section, setSection] = useState<Section>('general')
  const { t } = useLocale()
  return <section className="settings-page"><header className="page-heading"><div><span className="section-index">{t('SYSTEM CONFIGURATION / 03', 'SİSTEM YAPILANDIRMASI / 03')}</span><h1>{t('Systems', 'Sistemler')}</h1><p>{t('Configure every link, preference, and privacy boundary.', 'Tüm bağlantıları, tercihleri ve gizlilik sınırlarını yapılandır.')}</p></div><div className="heading-mark">S</div></header><div className="settings-layout"><nav className="settings-nav" aria-label={t('Settings categories', 'Ayar kategorileri')}>{sections.map(item => <button key={item.id} className={section === item.id ? 'active' : ''} onClick={() => setSection(item.id)}><Icon name={item.icon} /><span>{t(item.label, item.labelTr)}</span></button>)}</nav><div className="settings-content">{section === 'ai' || section === 'stt' || section === 'tts' ? <ProviderManager kind={section as ProviderKind} online={online} /> : <SettingsSection section={section} />}</div></div></section>
}
function SettingsSection({ section }: { section: Exclude<Section, 'ai' | 'stt' | 'tts'> }) {
  const { settings, updateSettings, online, user, setUser } = useApp(); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState('')
  const { t } = useLocale()
  const change = async (patch: Partial<AppSettings>) => { setSaving(true); setNotice(''); try { await updateSettings(patch); setNotice(t('Settings synchronized.', 'Ayarlar eşitlendi.')) } catch (caught) { setNotice(caught instanceof Error ? caught.message : t('Setting could not be saved.', 'Ayar kaydedilemedi.')) } finally { setSaving(false) } }
  const logout = async () => { setSaving(true); try { await authApi.logout(); setUser(null) } catch (caught) { setNotice(caught instanceof Error ? caught.message : t('Could not sign out.', 'Çıkış yapılamadı.')) } finally { setSaving(false) } }
  let content: ReactNode
  if (section === 'general') content = <Panel title={t('General', 'Genel')} copy={t('Language and interaction defaults for this Xultron identity.', 'Bu Xultron kimliği için dil ve etkileşim varsayılanları.')}><Field label={t('Interface language', 'Arayüz dili')}><select className="field" value={settings.locale} onChange={event => void change({ locale: event.target.value })}><option value="en">English</option><option value="tr">Türkçe</option></select></Field><Switch label={t('Reduced motion', 'Azaltılmış hareket')} description={t('Replace continuous transitions with calm state changes.', 'Sürekli animasyonları sakin durum geçişleriyle değiştir.')} checked={settings.reducedMotion} onChange={value => void change({ reducedMotion: value })} /></Panel>
  else if (section === 'voice') content = <VoicePanel settings={settings} change={change} />
  else if (section === 'memory') content = <Panel title={t('Memory', 'Hafıza')} copy={t('Control whether Xultron may use retained personal context.', 'Xultron’un saklanan kişisel bağlamı kullanıp kullanamayacağını kontrol et.')}><Switch label={t('Memory enabled', 'Hafıza etkin')} description={t('Pause all memory use without deleting existing records.', 'Kayıtları silmeden tüm hafıza kullanımını duraklat.')} checked={settings.memoryEnabled} onChange={value => void change({ memoryEnabled: value })} /><div className="settings-callout"><Icon name="memory" /><div><strong>{t('Direct control', 'Doğrudan kontrol')}</strong><p>{t('Search, edit, and permanently clear records from the Memory interface.', 'Hafıza arayüzünden kayıtları ara, düzenle ve kalıcı olarak temizle.')}</p></div></div></Panel>
  else if (section === 'appearance') content = <Panel title={t('Appearance', 'Görünüm')} copy={t("A precise interface that adapts without losing Xultron's identity.", 'Xultron kimliğini kaybetmeden uyum sağlayan hassas bir arayüz.')}><Field label={t('Surface depth', 'Yüzey derinliği')}><select className="field" value={settings.theme} onChange={event => void change({ theme: event.target.value as AppSettings['theme'] })}><option value="dark">{t('Graphite', 'Grafit')}</option><option value="darker">{t('Deep void', 'Derin boşluk')}</option></select></Field><Field label={t('System accent', 'Sistem vurgu rengi')}><select className="field" value={settings.accent} onChange={event => void change({ accent: event.target.value as AppSettings['accent'] })}><option value="cyan">{t('Ion cyan', 'İyon camgöbeği')}</option><option value="violet">{t('Electric violet', 'Elektrik moru')}</option></select></Field><Field label={t('Text scale', 'Metin ölçeği')}><select className="field" value={settings.textScale} onChange={event => void change({ textScale: event.target.value as AppSettings['textScale'] })}><option value="compact">{t('Compact', 'Kompakt')}</option><option value="standard">{t('Standard', 'Standart')}</option><option value="large">{t('Large', 'Büyük')}</option></select></Field></Panel>
  else if (section === 'network') content = <NetworkPanel settings={settings} change={change} />
  else if (section === 'privacy') content = <Panel title={t('Privacy', 'Gizlilik')} copy={t('Nothing should be retained silently. Analytics is off by default.', 'Hiçbir şey sessizce saklanmaz. Analitik varsayılan olarak kapalıdır.')}><Switch label={t('Conversation history', 'Sohbet geçmişi')} description={t('Store conversation sequences on your Xultron backend.', 'Sohbet dizilerini Xultron backend üzerinde sakla.')} checked={settings.conversationHistory} onChange={value => void change({ conversationHistory: value })} /><Switch label={t('Voice history', 'Ses geçmişi')} description={t('Consent preference for retaining voice-derived text in supported flows.', 'Desteklenen akışlarda sesten üretilen metni saklama izni.')} checked={settings.voiceHistory} onChange={value => void change({ voiceHistory: value })} /><Switch label={t('Save audio', 'Sesi kaydet')} description={t('Consent preference for future audio persistence. This release does not store raw audio.', 'Gelecekteki ses saklama tercihi. Bu sürüm ham sesi saklamaz.')} checked={settings.saveAudio} onChange={value => void change({ saveAudio: value })} /><Switch label={t('Anonymous analytics', 'Anonim analitik')} description={t('Share optional product telemetry. Never includes conversation or credentials.', 'İsteğe bağlı ürün telemetrisi paylaş. Sohbet veya kimlik bilgileri asla dahil edilmez.')} checked={settings.analytics} onChange={value => void change({ analytics: value })} /><div className="security-note"><Icon name="shield" /><div><strong>{t('Secrets stay server-side', 'Gizli bilgiler sunucuda kalır')}</strong><p>{t('Provider keys are submitted over the authenticated connection, then removed from browser state. Xultron never puts them in localStorage or sessionStorage.', 'Sağlayıcı anahtarları doğrulanmış bağlantı üzerinden gönderilir ve tarayıcı durumundan kaldırılır. Xultron bunları tarayıcı depolamasına yazmaz.')}</p></div></div></Panel>
  else if (section === 'account') content = <AccountPanel user={user!} online={online} onLogout={() => void logout()} onUpgrade={next => setUser(next)} />
  else content = <DevicesPanel online={online} />
  return <>{content}{saving && <div className="save-indicator"><Spinner /> {t('SYNCING', 'EŞİTLENİYOR')}</div>}{notice && <div className="settings-notice" role="status">{notice}</div>}</>
}
function Panel({ title, copy, children }: { title: string; copy: string; children: ReactNode }) { return <div className="settings-panel"><div className="settings-section-head"><div><h2>{title}</h2><p>{copy}</p></div></div><div className="settings-controls">{children}</div></div> }
function VoicePanel({ settings, change }: { settings: AppSettings; change: (patch: Partial<AppSettings>) => Promise<void> }) {
  const [preferredVoice, setPreferredVoice] = useState(settings.preferredVoice)
  const { t } = useLocale()
  useEffect(() => setPreferredVoice(settings.preferredVoice), [settings.preferredVoice])
  return <Panel title={t('Voice', 'Ses')} copy={t('Tune speech recognition and output without binding Xultron to one provider.', 'Xultron’u tek sağlayıcıya bağlamadan ses tanıma ve çıkışını ayarla.')}>
    <Field label={t('Recognition language', 'Tanıma dili')}><select className="field" value={settings.sttLanguage} onChange={event => void change({ sttLanguage: event.target.value })}><option value="auto">{t('Auto detect', 'Otomatik algıla')}</option><option value="en">English</option><option value="tr">Türkçe</option><option value="es">Español</option><option value="fr">Français</option><option value="de">Deutsch</option></select></Field>
    <form className="voice-preference-form" onSubmit={event => { event.preventDefault(); if (preferredVoice !== settings.preferredVoice) void change({ preferredVoice }) }}><Field label={t('Preferred voice', 'Tercih edilen ses')} hint={t('Saved only when you activate Apply Voice.', 'Yalnızca Sesi Uygula düğmesine basınca kaydedilir.')}><Input value={preferredVoice} maxLength={120} placeholder={t('Provider default', 'Sağlayıcı varsayılanı')} onChange={event => setPreferredVoice(event.target.value.slice(0, 120))} /></Field><Button type="submit" variant="secondary" disabled={preferredVoice === settings.preferredVoice}>{t('APPLY VOICE', 'SESİ UYGULA')}</Button></form>
    <Switch label={t('Voice history', 'Ses geçmişi')} description={t('Consent preference for supported transcript-retention flows.', 'Desteklenen transkript saklama akışları için izin tercihi.')} checked={settings.voiceHistory} onChange={value => void change({ voiceHistory: value })} />
  </Panel>
}
function NetworkPanel({ settings, change }: { settings: AppSettings; change: (patch: Partial<AppSettings>) => Promise<void> }) { const usage = useDataUsage(); const { t } = useLocale(); return <Panel title={t('Network', 'Ağ')} copy={t("Minimize data use and inspect this device's private session meter.", 'Veri kullanımını azalt ve bu cihazın özel oturum sayacını incele.')}><Switch label={t('Low data mode', 'Düşük veri modu')} description={t('Loads shorter histories, removes nonessential Core layers, avoids polling, and reduces motion.', 'Daha kısa geçmiş yükler, gereksiz Çekirdek katmanlarını kaldırır ve hareketi azaltır.')} checked={settings.lowDataMode} onChange={value => void change({ lowDataMode: value })} /><div className="data-meter"><span className="section-index">{t('SESSION DATA', 'OTURUM VERİSİ')}</span><div><p><Icon name="download" /><span>{t('Received', 'Alınan')}</span><strong>{formatBytes(usage.downloaded)}</strong></p><p><Icon name="upload" /><span>{t('Sent', 'Gönderilen')}</span><strong>{formatBytes(usage.uploaded)}</strong></p></div><button onClick={resetDataUsage}>{t('RESET METER', 'SAYACI SIFIRLA')}</button><small>{t('Estimated locally. No usage analytics are transmitted.', 'Yerel olarak tahmin edilir. Kullanım analitiği gönderilmez.')}</small></div></Panel> }
function AccountPanel({ user, online, onLogout, onUpgrade }: { user: NonNullable<ReturnType<typeof useApp>['user']>; online: boolean; onLogout: () => void; onUpgrade: (user: NonNullable<ReturnType<typeof useApp>['user']>) => void }) {
  const [sessions, setSessions] = useState<SessionDevice[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const { t, locale } = useLocale()
  useEffect(() => { let active = true; setSessions([]); setError(''); if (online && !user.isGuest) void authApi.sessions().then(result => { if (active) setSessions(result.sessions) }).catch(caught => { if (active) setError(caught instanceof Error ? caught.message : 'Sessions could not be loaded.') }); return () => { active = false } }, [online, user.id, user.isGuest])
  const upgrade = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const password = String(data.get('password')); if (password.length < 10) { setError('Use at least 10 characters.'); return } setBusy(true); try { const result = await authApi.register({ username: String(data.get('username')), email: String(data.get('email')), password }); onUpgrade(result.user) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Guest upgrade failed.') } finally { setBusy(false) } }
  const revoke = async (id: string) => { try { await authApi.revokeSession(id); setSessions(current => current.filter(item => item.id !== id)) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Session could not be revoked.') } }
  return <Panel title={t('Account', 'Hesap')} copy={t('Identity and active session controls.', 'Kimlik ve etkin oturum kontrolleri.')}><div className="identity-block"><span>{user.username.slice(0, 1).toUpperCase()}</span><div><strong>{user.username}</strong><p>{user.isGuest ? t('Temporary guest identity', 'Geçici misafir kimliği') : user.email || t('No email configured', 'E-posta yapılandırılmadı')}</p></div></div>{user.isGuest && <form className="upgrade-form" onSubmit={upgrade}><span className="section-index">{t('PRESERVE GUEST DATA', 'MİSAFİR VERİSİNİ KORU')}</span><p>{t('Create an identity to keep this conversation space.', 'Bu sohbet alanını korumak için bir kimlik oluştur.')}</p><Field label={t('Username', 'Kullanıcı adı')}><Input name="username" required minLength={3} /></Field><Field label="Email"><Input name="email" type="email" required /></Field><Field label={t('Password', 'Parola')}><Input name="password" type="password" required minLength={10} autoComplete="new-password" /></Field><Button type="submit" disabled={busy || !online}>{busy ? <Spinner /> : t('UPGRADE IDENTITY', 'KİMLİĞİ YÜKSELT')}</Button></form>}{!user.isGuest && <div className="session-list"><span className="section-index">{t('ACTIVE SESSIONS', 'ETKİN OTURUMLAR')}</span>{sessions.map(session => <div key={session.id}><span><strong>{session.current ? t('This device', 'Bu cihaz') : t('Xultron session', 'Xultron oturumu')}</strong><small>{t('Last active', 'Son etkinlik')} {new Date(session.lastSeenAt).toLocaleDateString(locale)} · {t('expires', 'bitiş')} {new Date(session.expiresAt).toLocaleDateString(locale)}</small></span>{!session.current && <button onClick={() => void revoke(session.id)}>{t('REVOKE', 'İPTAL ET')}</button>}</div>)}</div>}{error && <div className="inline-error">{error}</div>}<Button variant="danger" onClick={onLogout} disabled={!online}><Icon name="logout" /> {t('SIGN OUT', 'ÇIKIŞ YAP')}</Button></Panel>
}
export function DevicesPanel({ online }: { online: boolean }) { const [devices, setDevices] = useState<Device[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const { t } = useLocale(); useEffect(() => { let active = true; setDevices([]); setError(''); if (!online) { setLoading(false); return () => { active = false } } setLoading(true); void settingsApi.devices().then(result => { if (active) setDevices(result.devices) }).catch(caught => { if (active) setError(caught instanceof Error ? caught.message : t('Devices could not be loaded.', 'Cihazlar yüklenemedi.')) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [online, t]); return <Panel title={t('Devices', 'Cihazlar')} copy={t('Reserved links for future Raspberry Pi, ESP32, Bluetooth, sensors, and actuators.', 'Gelecekteki Raspberry Pi, ESP32, Bluetooth, sensör ve aktüatör bağlantıları için ayrılmış alan.')} >{error && <div className="inline-error" role="alert">{error}</div>}{loading ? <div className="center-loader"><Spinner /></div> : devices.length ? <div className="device-list">{devices.map(device => <div key={device.id}><Icon name="devices" /><span><strong>{device.name}</strong><small>{device.deviceType} · {device.status}</small></span></div>)}</div> : <EmptyState title={t('No devices linked', 'Bağlı cihaz yok')} description={t('The secure device boundary is ready. Hardware controls are intentionally not enabled in this release.', 'Güvenli cihaz sınırı hazır. Donanım kontrolleri bu sürümde bilinçli olarak etkin değildir.')} />}</Panel> }
