import { useEffect, useState, type FormEvent, type ReactNode } from 'react'
import type { AppSettings, ProviderKind, SessionDevice, Device } from '../../types'
import { useApp } from '../../stores/AppContext'
import { authApi } from '../../services/authApi'
import { settingsApi } from '../../services/settingsApi'
import { resetDataUsage } from '../../services/apiClient'
import { formatBytes, useDataUsage } from '../../hooks/useNetwork'
import { Icon, type IconName } from '../../components/Icon'
import { Button, EmptyState, Field, Input, Spinner, Switch } from '../../components/ui'
import { ProviderManager } from './ProviderManager'

type Section = 'general' | 'ai' | 'stt' | 'tts' | 'voice' | 'memory' | 'appearance' | 'network' | 'privacy' | 'account' | 'devices'
const sections: { id: Section; label: string; icon: IconName }[] = [
  { id: 'general', label: 'General', icon: 'settings' }, { id: 'ai', label: 'AI Providers', icon: 'core' }, { id: 'stt', label: 'STT Providers', icon: 'mic' }, { id: 'tts', label: 'TTS Providers', icon: 'voice' }, { id: 'voice', label: 'Voice', icon: 'voice' }, { id: 'memory', label: 'Memory', icon: 'memory' }, { id: 'appearance', label: 'Appearance', icon: 'core' }, { id: 'network', label: 'Network', icon: 'signal' }, { id: 'privacy', label: 'Privacy', icon: 'shield' }, { id: 'account', label: 'Account', icon: 'user' }, { id: 'devices', label: 'Devices', icon: 'devices' },
]
export function SettingsPage() {
  const { online } = useApp(); const [section, setSection] = useState<Section>('general')
  return <section className="settings-page"><header className="page-heading"><div><span className="section-index">SYSTEM CONFIGURATION / 03</span><h1>Systems</h1><p>Configure every link, preference, and privacy boundary.</p></div><div className="heading-mark">S</div></header><div className="settings-layout"><nav className="settings-nav" aria-label="Settings categories">{sections.map(item => <button key={item.id} className={section === item.id ? 'active' : ''} onClick={() => setSection(item.id)}><Icon name={item.icon} /><span>{item.label}</span></button>)}</nav><div className="settings-content">{section === 'ai' || section === 'stt' || section === 'tts' ? <ProviderManager kind={section as ProviderKind} online={online} /> : <SettingsSection section={section} />}</div></div></section>
}
function SettingsSection({ section }: { section: Exclude<Section, 'ai' | 'stt' | 'tts'> }) {
  const { settings, updateSettings, online, user, setUser } = useApp(); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState('')
  const change = async (patch: Partial<AppSettings>) => { setSaving(true); setNotice(''); try { await updateSettings(patch); setNotice('Settings synchronized.') } catch (caught) { setNotice(caught instanceof Error ? caught.message : 'Setting could not be saved.') } finally { setSaving(false) } }
  const logout = async () => { setSaving(true); try { await authApi.logout(); setUser(null) } catch (caught) { setNotice(caught instanceof Error ? caught.message : 'Could not sign out.') } finally { setSaving(false) } }
  let content: ReactNode
  if (section === 'general') content = <Panel title="General" copy="Language and interaction defaults for this Xultron identity."><Field label="Interface language"><select className="field" value={settings.locale} onChange={event => void change({ locale: event.target.value })}><option value="en">English</option><option value="tr">Türkçe</option><option value="es">Español</option><option value="fr">Français</option><option value="de">Deutsch</option></select></Field><Switch label="Reduced motion" description="Replace continuous transitions with calm state changes." checked={settings.reducedMotion} onChange={value => void change({ reducedMotion: value })} /></Panel>
  else if (section === 'voice') content = <VoicePanel settings={settings} change={change} />
  else if (section === 'memory') content = <Panel title="Memory" copy="Control whether Xultron may use retained personal context."><Switch label="Memory enabled" description="Pause all memory use without deleting existing records." checked={settings.memoryEnabled} onChange={value => void change({ memoryEnabled: value })} /><div className="settings-callout"><Icon name="memory" /><div><strong>Direct control</strong><p>Search, edit, and permanently clear records from the Memory interface.</p></div></div></Panel>
  else if (section === 'appearance') content = <Panel title="Appearance" copy="A precise interface that adapts without losing Xultron's identity."><Field label="Surface depth"><select className="field" value={settings.theme} onChange={event => void change({ theme: event.target.value as AppSettings['theme'] })}><option value="dark">Graphite</option><option value="darker">Deep void</option></select></Field><Field label="System accent"><select className="field" value={settings.accent} onChange={event => void change({ accent: event.target.value as AppSettings['accent'] })}><option value="cyan">Ion cyan</option><option value="violet">Electric violet</option></select></Field><Field label="Text scale"><select className="field" value={settings.textScale} onChange={event => void change({ textScale: event.target.value as AppSettings['textScale'] })}><option value="compact">Compact</option><option value="standard">Standard</option><option value="large">Large</option></select></Field></Panel>
  else if (section === 'network') content = <NetworkPanel settings={settings} change={change} />
  else if (section === 'privacy') content = <Panel title="Privacy" copy="Nothing should be retained silently. Analytics is off by default."><Switch label="Conversation history" description="Store conversation sequences on your Xultron backend." checked={settings.conversationHistory} onChange={value => void change({ conversationHistory: value })} /><Switch label="Voice history" description="Retain voice transcripts." checked={settings.voiceHistory} onChange={value => void change({ voiceHistory: value })} /><Switch label="Save audio" description="Persist raw audio. Off is the private default." checked={settings.saveAudio} onChange={value => void change({ saveAudio: value })} /><Switch label="Anonymous analytics" description="Share optional product telemetry. Never includes conversation or credentials." checked={settings.analytics} onChange={value => void change({ analytics: value })} /><div className="security-note"><Icon name="shield" /><div><strong>Secrets stay server-side</strong><p>Provider keys are submitted over the authenticated connection, then removed from browser state. Xultron never puts them in localStorage or sessionStorage.</p></div></div></Panel>
  else if (section === 'account') content = <AccountPanel user={user!} online={online} onLogout={() => void logout()} onUpgrade={next => setUser(next)} />
  else content = <DevicesPanel online={online} />
  return <>{content}{saving && <div className="save-indicator"><Spinner /> SYNCING</div>}{notice && <div className="settings-notice" role="status">{notice}</div>}</>
}
function Panel({ title, copy, children }: { title: string; copy: string; children: ReactNode }) { return <div className="settings-panel"><div className="settings-section-head"><div><h2>{title}</h2><p>{copy}</p></div></div><div className="settings-controls">{children}</div></div> }
function VoicePanel({ settings, change }: { settings: AppSettings; change: (patch: Partial<AppSettings>) => Promise<void> }) {
  const [preferredVoice, setPreferredVoice] = useState(settings.preferredVoice)
  useEffect(() => setPreferredVoice(settings.preferredVoice), [settings.preferredVoice])
  return <Panel title="Voice" copy="Tune speech recognition and output without binding Xultron to one provider.">
    <Field label="Recognition language"><select className="field" value={settings.sttLanguage} onChange={event => void change({ sttLanguage: event.target.value })}><option value="auto">Auto detect</option><option value="en">English</option><option value="tr">Turkish</option><option value="es">Spanish</option><option value="fr">French</option><option value="de">German</option></select></Field>
    <form className="voice-preference-form" onSubmit={event => { event.preventDefault(); if (preferredVoice !== settings.preferredVoice) void change({ preferredVoice }) }}><Field label="Preferred voice" hint="Saved only when you activate Apply Voice."><Input value={preferredVoice} maxLength={160} placeholder="Provider default" onChange={event => setPreferredVoice(event.target.value.slice(0, 160))} /></Field><Button type="submit" variant="secondary" disabled={preferredVoice === settings.preferredVoice}>APPLY VOICE</Button></form>
    <Switch label="Voice history" description="Retain transcripts in conversation history. Raw audio follows Save Audio below." checked={settings.voiceHistory} onChange={value => void change({ voiceHistory: value })} />
  </Panel>
}
function NetworkPanel({ settings, change }: { settings: AppSettings; change: (patch: Partial<AppSettings>) => Promise<void> }) { const usage = useDataUsage(); return <Panel title="Network" copy="Minimize data use and inspect this device's private session meter."><Switch label="Low data mode" description="Loads shorter histories, removes nonessential Core layers, avoids polling, and reduces motion." checked={settings.lowDataMode} onChange={value => void change({ lowDataMode: value })} /><div className="data-meter"><span className="section-index">SESSION DATA</span><div><p><Icon name="download" /><span>Received</span><strong>{formatBytes(usage.downloaded)}</strong></p><p><Icon name="upload" /><span>Sent</span><strong>{formatBytes(usage.uploaded)}</strong></p></div><button onClick={resetDataUsage}>RESET METER</button><small>Estimated locally. No usage analytics are transmitted.</small></div></Panel> }
function AccountPanel({ user, online, onLogout, onUpgrade }: { user: NonNullable<ReturnType<typeof useApp>['user']>; online: boolean; onLogout: () => void; onUpgrade: (user: NonNullable<ReturnType<typeof useApp>['user']>) => void }) {
  const [sessions, setSessions] = useState<SessionDevice[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => { if (online && !user.isGuest) authApi.sessions().then(result => setSessions(result.sessions)).catch(() => undefined) }, [online, user.isGuest])
  const upgrade = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const password = String(data.get('password')); if (password.length < 10) { setError('Use at least 10 characters.'); return } setBusy(true); try { const result = await authApi.register({ username: String(data.get('username')), email: String(data.get('email')), password }); onUpgrade(result.user) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Guest upgrade failed.') } finally { setBusy(false) } }
  const revoke = async (id: string) => { try { await authApi.revokeSession(id); setSessions(current => current.filter(item => item.id !== id)) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Session could not be revoked.') } }
  return <Panel title="Account" copy="Identity and active session controls."><div className="identity-block"><span>{user.username.slice(0, 1).toUpperCase()}</span><div><strong>{user.username}</strong><p>{user.isGuest ? 'Temporary guest identity' : user.email || 'No email configured'}</p></div></div>{user.isGuest && <form className="upgrade-form" onSubmit={upgrade}><span className="section-index">PRESERVE GUEST DATA</span><p>Create an identity to keep this conversation space.</p><Field label="Username"><Input name="username" required minLength={3} /></Field><Field label="Email"><Input name="email" type="email" required /></Field><Field label="Password"><Input name="password" type="password" required minLength={10} autoComplete="new-password" /></Field><Button type="submit" disabled={busy || !online}>{busy ? <Spinner /> : 'UPGRADE IDENTITY'}</Button></form>}{!user.isGuest && <div className="session-list"><span className="section-index">ACTIVE SESSIONS</span>{sessions.map(session => <div key={session.id}><span><strong>{session.current ? 'This device' : 'Xultron session'}</strong><small>Last active {new Date(session.lastSeenAt).toLocaleDateString()} · expires {new Date(session.expiresAt).toLocaleDateString()}</small></span>{!session.current && <button onClick={() => void revoke(session.id)}>REVOKE</button>}</div>)}</div>}{error && <div className="inline-error">{error}</div>}<Button variant="danger" onClick={onLogout} disabled={!online}><Icon name="logout" /> SIGN OUT</Button></Panel>
}
export function DevicesPanel({ online }: { online: boolean }) { const [devices, setDevices] = useState<Device[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { if (!online) { setLoading(false); return } settingsApi.devices().then(result => setDevices(result.devices)).finally(() => setLoading(false)) }, [online]); return <Panel title="Devices" copy="Reserved links for future Raspberry Pi, ESP32, Bluetooth, sensors, and actuators.">{loading ? <div className="center-loader"><Spinner /></div> : devices.length ? <div className="device-list">{devices.map(device => <div key={device.id}><Icon name="devices" /><span><strong>{device.name}</strong><small>{device.deviceType} · {device.status}</small></span></div>)}</div> : <EmptyState title="No devices linked" description="The secure device boundary is ready. Hardware controls are intentionally not enabled in this release." />}</Panel> }
