import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { AppProvider, useApp } from '../stores/AppContext'

const auth = vi.hoisted(() => ({ session: vi.fn() }))
const settingsApiMock = vi.hoisted(() => ({ get: vi.fn(), update: vi.fn(), devices: vi.fn() }))
vi.mock('../services/authApi', () => ({ authApi: auth }))
vi.mock('../services/settingsApi', async original => { const actual = await original<typeof import('../services/settingsApi')>(); return { ...actual, settingsApi: settingsApiMock } })
function Probe() { const { coreState, settings, sessionReachable, updateSettings, setUser, activeConversationId, activeDraft, setActiveConversationId, setActiveDraft } = useApp(); return <div><span data-testid="core">{coreState}</span><span data-testid="reachable">{String(sessionReachable)}</span><span data-testid="low">{String(settings.lowDataMode)}</span><span data-testid="locale">{settings.locale}</span><span data-testid="conversation">{activeConversationId ?? ''}</span><span data-testid="draft">{activeDraft}</span><button onClick={() => void updateSettings({ lowDataMode: true, reducedMotion: true })}>conserve</button><button onClick={() => void updateSettings({ locale: 'tr' })}>turkish</button><button onClick={() => setUser({ id: 'u2', username: 'orbit', email: null, isGuest: false, createdAt: '' })}>switch user</button><button onClick={() => setUser(null)}>logout</button><button onClick={() => { setActiveConversationId('conversation-1'); setActiveDraft('unfinished') }}>open conversation</button></div> }
function deferred<T>() { let resolve!: (value: T) => void; const promise = new Promise<T>(next => { resolve = next }); return { promise, resolve } }
describe('offline recovery and conservation behavior', () => {
  beforeEach(() => { Object.defineProperty(navigator, 'onLine', { configurable: true, value: true }); auth.session.mockResolvedValue({ user: { id: 'u1', username: 'nova', email: 'n@x.test', isGuest: false, createdAt: '' }, csrfToken: 'c', expiresAt: null }); settingsApiMock.get.mockResolvedValue({ settings: {} }); settingsApiMock.update.mockResolvedValue({ settings: { lowDataMode: true, reducedMotion: true } }) })
  it('completes the initial boot handshake', async () => { render(<AppProvider><Probe /></AppProvider>); await waitFor(() => expect(screen.getByTestId('core')).toHaveTextContent('ONLINE'), { timeout: 1800 }) })
  it('moves offline immediately and reconnects to online', async () => { render(<AppProvider><Probe /></AppProvider>); await waitFor(() => expect(screen.getByTestId('core')).toHaveTextContent(/CONNECTING|ONLINE/)); fireEvent(window, new Event('offline')); expect(screen.getByTestId('core')).toHaveTextContent('OFFLINE'); fireEvent(window, new Event('online')); await waitFor(() => expect(screen.getByTestId('core')).toHaveTextContent('ONLINE'), { timeout: 1200 }) })
  it('applies low-data and reduced-motion modes at the document boundary', async () => { render(<AppProvider><Probe /></AppProvider>); await waitFor(() => expect(screen.getByTestId('core')).toHaveTextContent('ONLINE'), { timeout: 1800 }); fireEvent.click(screen.getByText('conserve')); await waitFor(() => expect(document.documentElement.dataset.lowData).toBe('true')); expect(document.documentElement.dataset.reduceMotion).toBe('true'); expect(screen.getByTestId('low')).toHaveTextContent('true') })
  it('applies a language change immediately to state and the document', async () => {
    settingsApiMock.update.mockResolvedValueOnce({ settings: { locale: 'tr' } })
    render(<AppProvider><Probe /></AppProvider>)
    await waitFor(() => expect(screen.getByTestId('core')).toHaveTextContent('ONLINE'), { timeout: 1800 })
    fireEvent.click(screen.getByText('turkish'))
    await waitFor(() => expect(screen.getByTestId('locale')).toHaveTextContent('tr'))
    expect(document.documentElement.lang).toBe('tr')
    expect(document.documentElement.dataset.locale).toBe('tr')
  })
  it('keeps the Core out of ONLINE when the backend probe fails', async () => {
    auth.session.mockRejectedValue(new Error('backend unavailable'))
    render(<AppProvider><Probe /></AppProvider>)
    await waitFor(() => expect(screen.getByTestId('core')).toHaveTextContent('ERROR'), { timeout: 1800 })
    expect(screen.getByTestId('reachable')).toHaveTextContent('false')
  })
  it('resets settings on identity changes and ignores a prior user response that arrives late', async () => {
    const first = deferred<{ settings: { lowDataMode: boolean; locale: string } }>(); const second = deferred<{ settings: { lowDataMode: boolean; locale: string } }>()
    settingsApiMock.get.mockReturnValueOnce(first.promise).mockReturnValueOnce(second.promise)
    render(<AppProvider><Probe /></AppProvider>)
    await waitFor(() => expect(settingsApiMock.get).toHaveBeenCalledTimes(1))
    fireEvent.click(screen.getByText('switch user'))
    expect(screen.getByTestId('low')).toHaveTextContent('false'); expect(screen.getByTestId('locale')).toHaveTextContent('en')
    await waitFor(() => expect(settingsApiMock.get).toHaveBeenCalledTimes(2))
    second.resolve({ settings: { lowDataMode: false, locale: 'tr' } }); await waitFor(() => expect(screen.getByTestId('locale')).toHaveTextContent('tr'))
    first.resolve({ settings: { lowDataMode: true, locale: 'fr' } }); await Promise.resolve(); expect(screen.getByTestId('locale')).toHaveTextContent('tr'); expect(screen.getByTestId('low')).toHaveTextContent('false')
    fireEvent.click(screen.getByText('logout')); expect(screen.getByTestId('locale')).toHaveTextContent('en'); expect(screen.getByTestId('low')).toHaveTextContent('false')
  })
  it('does not apply a completed settings mutation to a different identity', async () => {
    const update = deferred<{ settings: { lowDataMode: boolean; locale: string } }>()
    settingsApiMock.update.mockReturnValueOnce(update.promise)
    render(<AppProvider><Probe /></AppProvider>)
    await waitFor(() => expect(settingsApiMock.get).toHaveBeenCalled())
    fireEvent.click(screen.getByText('conserve'))
    await waitFor(() => expect(settingsApiMock.update).toHaveBeenCalled())
    fireEvent.click(screen.getByText('switch user'))
    expect(screen.getByTestId('low')).toHaveTextContent('false')
    update.resolve({ settings: { lowDataMode: true, locale: 'fr' } })
    await Promise.resolve()
    expect(screen.getByTestId('locale')).not.toHaveTextContent('fr')
    expect(screen.getByTestId('low')).toHaveTextContent('false')
  })
  it('keeps the active conversation and draft while settings change', async () => {
    render(<AppProvider><Probe /></AppProvider>)
    await waitFor(() => expect(screen.getByTestId('core')).toHaveTextContent('ONLINE'), { timeout: 1800 })
    fireEvent.click(screen.getByText('open conversation'))
    fireEvent.click(screen.getByText('turkish'))
    expect(screen.getByTestId('conversation')).toHaveTextContent('conversation-1')
    expect(screen.getByTestId('draft')).toHaveTextContent('unfinished')
  })
})
